# -*- coding: utf-8 -*-
"""把英文摘要词数调整到模板要求的 200 实词左右"""

import os
import re

EN = {}

EN['p1_part1.md'] = """Recycled aggregate concrete is produced by crushing and screening waste concrete and reusing it as aggregate, which can ease both the pressure of construction waste storage and the shortage of natural sand and gravel resources. Taking a 30-storey apartment project with a height of nearly 100 m in Guangxi as the research object, this paper evaluates the application of recycled aggregate concrete with a replacement ratio of 30% and a total dosage of about 10679 m3. An evaluation index system is established from three dimensions: technical performance, construction adaptability, and economic and environmental benefits. Combined with the mix proportion design, component production and entity inspection data, the applicability of recycled concrete in high-rise shear wall structures is analysed. The results show that under the condition of 30% replacement ratio, the compressive strength, elastic modulus and durability of recycled aggregate concrete can meet the design requirements, and the slightly lower elastic modulus helps to optimize the structural stiffness distribution and improve the internal force distribution under earthquake action. However, problems such as workability fluctuation caused by the high water absorption of recycled aggregate and the large discreteness of component quality still need to be controlled. Countermeasures including strengthening the classification and pretreatment of recycled aggregate, optimizing mix proportion parameters and improving the whole-process quality records are put forward."""

EN['p2_part1.md'] = """Prefabricated construction can transfer a large amount of wet work to factories, reduce site labor and urban disturbance, and is an important direction for the industrial construction of utility tunnels. Taking the Mianyang utility tunnel project as the research object, this paper investigates the quality problems in prefabricated construction and analyses their causes, and puts forward optimization countermeasures for the quality management system, aiming at the national largest prefabricated utility tunnel with a total tunnel length of about 25.15 km and 27.14 km supporting municipal roads. Typical quality problems and their causes are sorted out from five dimensions of man, machine, material, method and environment, covering component acceptance, hoisting positioning, joint waterproofing, sleeve connection and multi-discipline construction. Targeted measures are proposed from three aspects of organization management, process technology and quality control means, including establishing the component batch traceability system, implementing resident factory supervision, applying the BIM and 3D scanning combined deviation dynamic correction technology, and adopting the pre-laid inverted and self-healing polymer waterproof membrane composite technology. The countermeasures have been applied in the project, with the installation qualification rate of embedded parts reaching 100% and zero defect achieved in structural quality, which provides a reference for similar large-scale prefabricated municipal projects."""

EN['p3_part1.md'] = """BIM collaborative design is an important technical means to improve the structural design quality of prefabricated buildings. Taking the S8-01 municipal affordable housing project in Pudong Town, Minhang District, Shanghai as the research object, this paper analyses the application effect of BIM collaborative design from the perspective of structural design quality, based on the fact that the project has a total building area of about 110000 m2, adopts the assembled integral shear wall system and the prefabricated building ratio reaches 100%. The influence mechanism of BIM collaborative design is analysed from four dimensions: design collaboration, component deepening, pipeline integration and design change. Combined with the project practices in parametric component library construction, collision inspection, joint optimization and design-production data connection, its role in reducing component size errors, embedded part position deviation and conflicts between pipelines and structural components is discussed. The results show that BIM collaborative design can significantly improve the one-time yield rate of design. In view of the existing problems such as insufficient collaboration depth and discontinuous data transmission, countermeasures including strengthening whole-specialty collaboration, promoting design-production integration and strengthening personnel training are put forward."""

if __name__ == '__main__':
    base = os.path.dirname(os.path.abspath(__file__))
    for fn, new_en in EN.items():
        path = os.path.join(base, fn)
        s = open(path, encoding='utf-8').read()
        s2 = re.sub(r'(@@ABSTRACT_EN@@\s*)(.*?)(\s*@@KEYWORDS_EN@@)',
                    lambda m: m.group(1) + new_en + m.group(3), s, flags=re.S)
        open(path, 'w', encoding='utf-8').write(s2)
        print(f'{fn}: 英文摘要词数 = {len(new_en.split())}')
